### ISSUE TITLE
Changes in why recruit section of Home page

### ISSUE THREAD

**Issue by itsGyanendra** [abhishekshree/spo-website#100]
Add one more card
### **Selection Process**
IIT Kanpur is home to the brightest individuals in India who have been accepted through a rigorous screening procedure like JEE Advanced, Gate etc.

Change order to 
Academics, Ranking, Alumni, Selection Process, Research and Development, All-round development

Add icons in each card.
### **Academics**
![image](https://user-images.githubusercontent.com/60781567/171992785-f2ff6c17-9171-4f32-9fcd-af2e07328ff1.png)

### **Ranking**
![image](https://user-images.githubusercontent.com/60781567/171992815-3b8436f9-bb49-410e-8b38-1d89bcab7884.png)

### **Alumni**
![image](https://user-images.githubusercontent.com/60781567/171992785-f2ff6c17-9171-4f32-9fcd-af2e07328ff1.png)

### **Selection Process**
![image](https://user-images.githubusercontent.com/60781567/171992862-74622e22-c0bb-4e76-9c46-3fc0e6f0f970.png)

### **Reserach and Development**
![image](https://user-images.githubusercontent.com/60781567/171992875-ae244efc-fb98-4281-8fe3-f8f112d24f57.png)

### **All-round Development**

![image](https://user-images.githubusercontent.com/60781567/171992884-01771474-f5a9-40e5-bf2c-e6abe53c89e6.png)

**Comment by abhishekshree** [comment]
@ahujatejas06 take this one
