### ISSUE TITLE
Fix these links

### ISSUE THREAD

**Issue by 1-Harshit** [abhishekshree/spo-website#28]
https://github.com/abhishekshree/spo-website/blob/f93df4e105a66fd1561af2fd59b3980757715e09/pages/companies.tsx#L303-L304

**Comment by 1-Harshit** [comment]
https://github.com/abhishekshree/spo-website/blob/f93df4e105a66fd1561af2fd59b3980757715e09/pages/departmental-brochure.tsx#L7-L102

**Comment by ahujatejas06** [comment]
Claim
