### ISSUE TITLE
Add navigation links in the companies and students section.

### ISSUE THREAD

**Issue by abhishekshree** [abhishekshree/spo-website#53]
- We need internal links for both the pages in a subtle way.

**Comment by 1-Harshit** [comment]
wdym?

**Comment by abhishekshree** [comment]
Example: Going to the FAQ section directly from the top of Companies page

**Comment by amdpt323** [comment]
how about creating a side nav bar that directly jumps you into the different sections of a particular page !

**Comment by 1-Harshit** [comment]
Go ahead, work on it! Take someone's help if need be.

**Comment by abhishekshree** [comment]
Need this by tomorrow EOD @amdpt323
