### ISSUE TITLE
Changes in About IITK Page

### ISSUE THREAD

**Issue by itsGyanendra** [abhishekshree/spo-website#82]
Add in-page navigation to his page also.

1. About IIT Kanpur
2. Academics at IIT Kanpur
3. Research and Development
4. Alumni
5. Faculty
6. Students' Life and Activities.

### **About IIT Kanpur**
Add a new section on this page.

Indian Institute of Technology, Kanpur, established in 1959, is one of the premier institutions established by the Government of India. The aim of the Institute is to provide meaningful education, conduct original research of the highest standard and provide leadership in technological innovation.  Consistently ranked amongst the top 5 engineering institutes in India over past several decades. IIT Kanpur offers courses in sciences, engineering, humanities and management. The students go to get the best of opportunities in the form of highly advanced courses, eminent faculty members, well-equipped laboratories, library, hostels and immense facilities to excel in research and development. The selection procedure for students at undergraduate, postgraduate and research level is highly stringent so that IIT gets the best brains of India. Highly scientific and innovative technology is used for teaching and conducting research activities. Every year IIT Kanpur is enriched by the laurels brought by the faculty members and the students in the form of research publications, projects, fellowships and industrial exposure. Many of our alumni are leaders in academia and industry around the globe. The sprawling IIT Kanpur campus is located in the industrial city of Kanpur, only a few hours away from New Delhi, the Capital of India.

### **Programs at IITK**
Change heading  to **Academics at IIT Kanpur**
Add the below content after heading - 
Academics at IIT Kanpur empowers the students with a critical thinking led approach, scientific temperament and knowledge in science, engineering, management and humanities fields to solve problems that challenge humanity. The globally acclaimed education prepares the students for rewarding and exciting careers. The excellent education has enabled the alumni to succeed in diverse fields.

List of academics programs at IIT Kanpur.
Change the programmes as shown below. You can find the text in the [Campus Recruitment Brochure](https://spo-abhishekshree.vercel.app/assets/IITK_Recruitment_Brochure_2021-22.pdf). Add one more programme to this - **PhD**

![image](https://user-images.githubusercontent.com/60781567/170792168-1ec2634b-7b65-4228-87b2-1b5c7fd3b372.png)

### **For research section**

Change heading to **Research and Development**

Remove the existing content. Also, you can add some photos of
 Lab..[ Photo Link](https://drive.google.com/drive/u/3/folders/1KjGQh8cS5fwtutUNbGlg57M_MpRtUFWa)

 ![image](https://user-images.githubusercontent.com/60781567/170794057-c4347ee2-6213-4373-81a9-8c4c658803c4.png)

### **For Alumni Sections**

Change the content by this. Also, add a line -

1) We have had many notable alumni who have received national and international recognition in their respective professional fields.
2) With more than 45000 alumni spanning across the globe, they have been instrumental in strengthening the image of I.I.T. Kanpur. 

Insert Line 1 after the music and social services and Line 2 after Humanitarian services. Also, you can add some photos of
 Alumni events

![image](https://user-images.githubusercontent.com/60781567/170794931-b36b45b3-ac34-4e15-bea7-ab3871edd338.png)

List down some of the Prominent alumni names also.

Some of the most notable alumni that IIT Kanpur boasts of producing are :

1. N.R Narayana Murthy - Founder of Infosys
2. Pradeep S. Sindhu - Founder, Vice Chairman & CTO - Juniper Networks
3. Dr Ashok Jhunjhunwala - Padma Shri & Professor of Electrical Engg at IIT Madras
4. Dr Ashoke Sen - FRS & Padma Shri, Famous String Theorist
5. Subir Bose - Managing Director - Berger Paints
6. Mahesh Behari Lal - Chairman & MD, Hindustan Petroleum Corporation Ltd.
7. Satish Kumar Kaura - Chairman - MD Samtel Colour Limited
8. Vijay Mahajan - Former Dean of the Indian School of Business
9. Duvvuri Subbarao - 22nd Governor of Reserve Bank of India
10. Pawan Kumar Goenka - Chief Operating Officer(COO) of Mahindra & Mahindra Ltd.
11. Late Professor Rajiv Motwani (Stanford University) - Backed the founders of Google & Paypal
12. Manindra Agarwal, Nitin Saxena & Neeraj Kayal - Gave the first deterministic primality-proving algorithm famously known as AKS Primality Test. Authors received the 2006 Godel Prize & the 2006 Fulkerson Prize for this result
13. Prof. Arvind - JOHNSON Professor , MIT, USA
14. Rajeev Chawla - Secretary of E-governance, Govt. of Karnataka

### **For Faculty section**
413 Faculty number. Correct it. Also add this photo [Link ](https://drive.google.com/drive/u/3/folders/1KjGQh8cS5fwtutUNbGlg57M_MpRtUFWa)

### **All Round Development Section and Festivals at IIT Kanpur**
Change heading to **Students' Life and Activities.**
Change content to:
![image](https://user-images.githubusercontent.com/60781567/170797120-0ead18d7-6d01-4931-8519-5b925951fc2a.png)
![image](https://user-images.githubusercontent.com/60781567/170797150-975f7dde-7257-4249-8ad5-342635db76fb.png)
![image](https://user-images.githubusercontent.com/60781567/170797191-964d1793-94fd-4518-9e28-bf5c646ddb66.png)

**Comment by 1-Harshit** [comment]
@Krishnansh5 pick this up

**Comment by Krishnansh5** [comment]
claim
