### ISSUE TITLE
Changes in Home Page

### ISSUE THREAD

**Issue by itsGyanendra** [abhishekshree/spo-website#83]
- Change the content - 

The Indian Institute of Technology Kanpur is well known for its academic excellence and is often considered as the 'first stop' for a large number of industries and other organizations for recruiting undergraduate and post-graduate students. We truly appreciate the faith bestowed on us from several organizations and we look forward to continuing our relationship with them. The Students' Placement Office (SPO) is run and managed by an efficient team of office staff & students and handles all aspects of placements at IIT Kanpur. Right from contacting companies to managing all logistics of arranging for tests, pre-placement talks and conducting final interviews the SPO team provides it's best possible assistance to the recruiters. The hospitality and the functioning of SPO is applauded and well received by the visiting recruiters every year.
by-
The Students' Placement Office (SPO), IIT Kanpur is maintained and managed by a dedicated team of office staff and students who are responsible for all areas of IIT Kanpur placements. The SPO team assists recruiters to the best of its ability. We are grateful for the trust placed in us by various organisations, and we hope to continue working with them in the future.

- Add side image of any IIT Kanpur building or anything related to IIT Kanpur

- Create two tabs .. Announcement and Events of SPO and Create two separate pages for the same. Announcement Include Registration of Companies, Students etc.  Events implies the session and event that SPO conducted across the year.

- Add Section, Why Recruit from IIT Kanpur
Set 6 cards for the same - 
1. Academics - Providing a rigorous and world-class academic experience with the help of distinguished faculty, amazing peer groups and carefully designed coursework. On click of this tab redirect it to about-iitk #academics
2. Ranking - 
3. Alumni - On click of this tab redirect it to about-iitk #alumni
4. Research and Development - Access to the latest and pioneering advances in technology with the aim of acclimating students to the innovations in the scientific community. On click of this tab redirect it to about-iitk #research
5. 
6. All-Round Development - Promoting the all-around development of students through a myriad of cultural and sports activities, fests, competitions and exhibitions. On click of this tab redirect it to about-iitk #student-activities

- Add Director Message, Chairman Message and Vice-Chairman message in the carousel.

**### News@IITK**
Add IITK in news section by embedding Iframe of Facebook and twitter of official handle of IITK
![image](https://user-images.githubusercontent.com/60781567/170799974-2ca0f797-9b64-4f79-9e91-3d9a7c36e465.png)

**Comment by 1-Harshit** [comment]
@utkarsh-tf141 take this up

**Comment by utkarsh-tf141** [comment]
claim

**Comment by itsGyanendra** [comment]
Update - 
Announcements and Events are just like the insights pages. You need to brainstorm how it can be incorporated into the home page also.
