### ISSUE TITLE
Changes in Department Brochures page

### ISSUE THREAD

**Issue by itsGyanendra** [abhishekshree/spo-website#84]
In the description of the page, it is mentioned that -Click on a department to download their brochure.

Clicking on the department redirects to the department home page.

It's better to have two separate things there.
1. Download the Brochure.
2. Visit Department Homepage

**Comment by 1-Harshit** [comment]
closed by https://github.com/abhishekshree/spo-website/commit/6e10a7e04259fab4234fb9ab8bdaff5333e7e5d8
