### ISSUE TITLE
Placement and Internship Insight Page

### ISSUE THREAD

**Issue by itsGyanendra** [abhishekshree/spo-website#85]
We have a total of around 70+ placement insights and 50+ Internship insights. Over the year we will have more insights. It's better to segregate the insights year wise and then by placement and internship for easy user navigation. Make something like that the URL of a particular page doesn't change even after 3-4 years.

Also, keep the format of insights as - 

### **Title :** {{Name}} : Summer Intern at {{Company}}

{{Name}}, studying in IIT Kanpur as a {{Programme}} student in {{Department}}  will do {{his/her}} summer internship in {{Profile}} profile at {{Company}}. Here are some brief insights of {{his/ hers}}. 

**Shortlisted Profiles & Companies**

{{Companies & Profiles}}

**Insights on the Selection Process**

{{Selection Process}}

**Preparation Resources**	

{{Resources}}

**Advice for students (dos and don’ts)?**

{{Advice}}

**Comment by 1-Harshit** [comment]
@amdpt323 This is yours

**Comment by amdpt323** [comment]
claim

**Comment by amdpt323** [comment]
so basically i have to create some thing like nav bar so that it segregates the insights on the year wise? dose it LGTU?

**Comment by 1-Harshit** [comment]
yeah and we can have something of a filter.

if the filename matches "2022-intern" place in 2022 intern insight.

Browine points for not hardcoding 2022

---
Regards
Harshit Raj
Sophomore Undergraduate
CSE, IIT Kanpur
1-Harshit.github.io/<https://1-harshit.github.io/>
________________________________

**Comment by 1-Harshit** [comment]
all the changes are in blog/index.html
