### ISSUE TITLE
Responsivness and other minor changes in About IITK Page

### ISSUE THREAD

**Issue by itsGyanendra** [abhishekshree/spo-website#94]
Add an image on the right side of the content for the below two sections and make it responsive for a larger screen. For the small screen, place the image on the bottom of the content just like as of now.

![image](https://user-images.githubusercontent.com/60781567/171982587-49b9b059-a702-48bc-af6c-8b0167497098.png)

![image](https://user-images.githubusercontent.com/60781567/171982710-ca832226-f50e-4e1d-8971-3547dc51b60c.png)

Add in the heading B.Tech / B.S / B.Des

![image](https://user-images.githubusercontent.com/60781567/171982728-1c3481ee-d4df-444d-a11b-d290e7699b59.png)

Add subheading under Academics at IITK: **List of Academic Programmes**
Order of Academic Programs:  

1. B.Tech / B.S / B.Des
2. Minor
3. Double Major
4. Bachelor-Master Dual Degree
5. M.Sc
6. M.Tech. / M.S.(R)
7. Master of Design (M.Des)
8. M.B.A
9. PhD

![image](https://user-images.githubusercontent.com/60781567/171983309-adfd96a0-a1aa-446c-ba65-0b3dcc808731.png)

This looks good but distorted in small screens

![image](https://user-images.githubusercontent.com/60781567/171983420-29609e0e-9412-4e5a-a622-85ade738284f.png)

Place the image just after heading (Faculty) for small screens.

These things need to be done for Research and Development section also.

![image](https://user-images.githubusercontent.com/60781567/171983589-a8387155-7782-4348-8ead-bce3fb7c1106.png)

Add more content to Udghosh.. Ye bhi apna hi fest hai :) Or remove irrelevant details from Techkriti and Antaragni.

**Comment by abhishekshree** [comment]
@utkarsh-tf141 take it up
