### ISSUE TITLE
Fix IFrame in homepage

### ISSUE THREAD

**Issue by itsGyanendra** [abhishekshree/spo-website#99]
![image](https://user-images.githubusercontent.com/60781567/171987345-ff934d20-7327-4711-b87f-8ee1936dfeac.png)

There is a difference in the size of  Twitter and Facebook Iframe. Facebook Iframe size seems fit.

![image](https://user-images.githubusercontent.com/60781567/171987384-bfa948ff-5e48-4273-9653-d8587cc2b03d.png)
 Facebook Iframe ?

**Comment by abhishekshree** [comment]
Facebook iframe is static, can't change

**Comment by abhishekshree** [comment]
Mobile view won't support the iframe, old SDK

**Comment by itsGyanendra** [comment]
there isn't any way to incorporate the Facebook iframe ?

**Comment by abhishekshree** [comment]
> there isn't any way to incorporate the Facebook iframe ?

Nope

**Comment by 1-Harshit** [comment]
Ah, here we go again. Looking at legacy issues. 

> > there isn't any way to incorporate the Facebook iframe ?
> 
> Nope

**Comment by abhishekshree** [comment]
> Ah, here we go again. Looking at legacy issues. 
> 
> > > there isn't any way to incorporate the Facebook iframe ?
> > 
> > Nope
> 
> 

Painful
